services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

    container_name: neo

    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./config:/config
      - ./plugins:/plugins

# docker compose up -d
# docker exec -it neo cypher-shell -u neo4j -p password

#----------------------------------------#
    
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo_tp
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #     MONGO_INITDB_DATABASE: project
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongodb/data:/data/db
  #     - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #   restart: always
